### ISSUE TITLE
Why include a `DirectedSpectrum` object?

### ISSUE THREAD

**Issue by jackgoffinet** [neil-gallagher/directed-spectrum#2]
Wouldn't it be easier for `ds` to return `ds_array`, `f`, and `cgroups` directly?

**Comment by neil-gallagher** [comment]
I chose to group the three outputs together as an object so that they are clearly linked. I expect this to mostly be useful when there are multiple different sets of directed spectrum features to keep track of and/or when directed spectrum values need to be saved and loaded again by different users.
