### ISSUE TITLE
Why are the diagonal elements of the DS zeros?

### ISSUE THREAD

**Issue by jackgoffinet** [neil-gallagher/directed-spectrum#4]
Shouldn't the diagonal elements be power spectral densities?

```python3
signal = np.random.randn(1,3,100)
dir_spec = ds(signal, 1.0, ['foo','bar', 'baz'], nperseg=100, noverlap=0)
fig, axarr = plt.subplots(nrows=3, ncols=3)
for i in range(3):
    for j in range(3):
        axarr[i,j].plot(dir_spec.ds_array[0,:,i,j].real)
plt.savefig('temp.pdf')
```

**Comment by neil-gallagher** [comment]
This has been partially fixed in a recent update where I have now implemented the 'self-directed spectrum'. This generalizes the definition of the directed spectrum to the case where the source and target are the same, based on the definition of transmitted signal in my NeurIPS 2021 paper. This 'self-directed spectrum' is not the same thing as the power spectrum. Also, it is not defined in the case of the pairwise directed spectrum, so the diagonals are returned as NaNs in that case.
